service:
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0
  logger:
    level: 10 # DEBUG level, see https://docs.python.org/2/library/logging.html#levels
#    level: 20 # INFO level
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

leecher:
  pgsql:
    dsn: host=127.0.0.1 dbname=ip_comparator user=ogaidukov password=
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0
  cleanup:
    backward_delay: 30 minutes
  logger:
    level: 10 # DEBUG level, see https://docs.python.org/2/library/logging.html#levels
#    level: 20 # INFO level
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"